[tool.poetry]
name = "nesy-verification"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "==3.10.13"
auto_lirpa = "*"
# auto-lirpa = { path = "/Users/edward/github/imperial/nesy-verification/auto_LiRPA" }
numpy = "^1.26.1"
torch = "^1.12.0"
black = "^23.10.1"
rich = "^13.6.0"
torchmetrics = "^1.2.0"
pylint = "^3.0.2"
torchvision = "^0.13.0"
scikit-learn = "^1.3.2"
tqdm = "*"
pandas = "*"
appdirs = "^1.4.4"
gurobipy = "^11.0.0"
pysdd = "^0.2.11"
graphviz = "^0.20.1"
pyarrow = "^15.0.0"

[tool.poetry.dev-dependencies]
black = "*"
isort = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
